import Head from "next/head";
import { Inter } from "next/font/google";
import cx from "classnames";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={cx(styles.main, inter.className)}>
        <h1>Hello Next World!</h1>
      </main>
    </>
  );
}
